# Generated by Django 4.1.1 on 2024-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artifactmodel",
            options={
                "verbose_name": "Artifact Model",
                "verbose_name_plural": "Artifact Models",
            },
        ),
        migrations.AlterField(
            model_name="artifactmodel",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="artifactmodel",
            name="lessonPlan",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="artifactmodel",
            name="longDescription",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="artifactmodel",
            name="model",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="artifactmodel",
            name="shortDescription",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="artifactmodel",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
