# Generated by Django 4.1.1 on 2024-10-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0005_alter_artifactmodel_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactmodel",
            name="thumbnail",
            field=models.ImageField(
                height_field=10, null=True, upload_to="static/", width_field=10
            ),
        ),
    ]
