# Generated by Django 5.1.5 on 2025-02-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0008_alter_artifactmodel_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("options", models.TextField()),
            ],
        ),
    ]
