# Generated by Django 4.1.1 on 2024-10-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtifactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("site", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("lessonPlan", models.IntegerField()),
                ("shortDescription", models.TextField()),
                ("longDescription", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="")),
                ("model", models.FileField(upload_to="")),
            ],
        ),
    ]
