# Generated by Django 4.1.1 on 2024-10-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "artifacts",
            "0002_alter_artifactmodel_options_alter_artifactmodel_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactmodel",
            name="model",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="artifactmodel",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
