# Generated by Django 4.1.1 on 2024-10-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0003_alter_artifactmodel_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactmodel",
            name="model",
            field=models.FileField(null=True, upload_to="static/"),
        ),
        migrations.AlterField(
            model_name="artifactmodel",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="static/"),
        ),
    ]
