# Generated by Django 4.1.1 on 2024-10-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0007_alter_artifactmodel_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactmodel",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="static/"),
        ),
    ]
